// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFZ2WzfRdIfYdFzEL5lqGeTbsKnle9SjE',
    appId: '1:1042458226381:web:673d88113a02283e5a0384',
    messagingSenderId: '1042458226381',
    projectId: 'ta-pago-19987',
    authDomain: 'ta-pago-19987.firebaseapp.com',
    storageBucket: 'ta-pago-19987.appspot.com',
    measurementId: 'G-59F0Q3LXNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4G8AiEatY5p-zLc1VIgL3V31jIhLZeo',
    appId: '1:1042458226381:android:b40e711cc95df7d95a0384',
    messagingSenderId: '1042458226381',
    projectId: 'ta-pago-19987',
    storageBucket: 'ta-pago-19987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaE8OOwXSMasAjDOK70LU6jpClToWnblE',
    appId: '1:1042458226381:ios:ee1a169d309a6f2f5a0384',
    messagingSenderId: '1042458226381',
    projectId: 'ta-pago-19987',
    storageBucket: 'ta-pago-19987.appspot.com',
    iosClientId: '1042458226381-4hm4cg71qkuaibu9deefccb4ucmm0kos.apps.googleusercontent.com',
    iosBundleId: 'com.example.taPago',
  );
}
